apiVersion: v1
data:
  config.json: |
    global:
    name: consul
    connectInject:
      enabled: true
    {
    "datacenter":"devqa"
    }
kind: ConfigMap
metadata:
  labels:
    app: consul
    app.kubernetes.io/instance: consul
    chart: consul-0.20.1
    heritage: Tiller
    release: consul
  name: consul-configuration
  namespace: monitoring
