apiVersion: v1
data:
  connection.json: |
    {
      "datacenter":"dc2"
    }
kind: ConfigMap
metadata:
  labels:
    app: consul
    app.kubernetes.io/instance: consul
    chart: consul-7.0.12
    heritage: Tiller
    release: consul
  name: consul-configuration
  namespace: monitoring
